language: node_js

node_js:
  - 0.10
  - 0.12
  - 4
  - 5
  - 6
  - 8
  - node
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "iojs"

notifications:
  email:
    recipients:
      - magic@wizardtales.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/509c88551a18006fe93f
    on_success: change
    on_failure: always
    on_start: false
<<<<<<< HEAD

os:
  - linux

matrix:
  allow_failures:
    - node_js: node
  fast_finish: true

sudo: false

cache:
  npm: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  mariadb: "10.0"

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;

before_script:
    - until nc -z localhost 27017 ; do echo Waiting for MongoDB; sleep 1; done
    - mysql -e "create database db_migrate_test;"
    - createdb db_migrate_test
    - cp test/db.config.ci test/db.config.json
